image: registry.gitlab.heu.group/docker-tools/pipelines:v8.18

variables:
  IMAGE_REPOSITORY: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG"
  IMAGE_TAG: "$CI_COMMIT_SHA"
  KUBE_NAMESPACE: ai

stages:
  - build
  - lint
  - test
  - terraform-plan
  - terraform-apply
  - deploy

include:
  - local: .gitlab/ci/lint.yaml
  - local: .gitlab/ci/build.yaml
  - local: .gitlab/ci/terraform.yaml
  - local: .gitlab/ci/deploy.yaml
  - local: .gitlab/ci/test.yaml
