services:
  postgresql:
    container_name: postgres-evaluation-app
    image: postgres:18 
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: alpharius

