services:
  postgresql:
    container_name: postgresql_ai_eval
    image: pgvector/pgvector:pg18
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: alpharius

