services:
  postgresql:
    container_name: postgresql-evaluation-app
    image: pgvector/pgvector:pg18
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: alpharius

