apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.name }}-access
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }} access
data:
  access.yaml: |
    {{- .Values.access | toYaml | nindent 4 }}
