apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }} api
spec:
  type: {{ .Values.services.api.type }}
  ports:
    - port: {{ .Values.services.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }} api
