{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.deployment.name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }} backend-secrets
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Release.Namespace }}
    kind: SecretStore
  target:
    name: {{ .Values.deployment.name }}-backend
  data:
    {{- range $key := list "APP_DB_PASSWORD" "OPENAI_API_KEY" "ANTHROPIC_API_KEY" }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $.Values.externalSecrets.vaultPath }}
        property: {{ $key }}
    {{- end }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.deployment.name }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }} frontend-secrets
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Release.Namespace }}
    kind: SecretStore
  target:
    name: {{ .Values.deployment.name }}-frontend
  data:
    {{- range $key := list "NUXT_OIDC_CLIENT_ID" "NUXT_OIDC_CLIENT_SECRET" "NUXT_SESSION_PASSWORD" }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $.Values.externalSecrets.vaultPath }}
        property: {{ $key }}
    {{- end }}
{{- end }}
