apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }} frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }} frontend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }} frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          securityContext:
            {{- toYaml .Values.frontendSecurityContext | nindent 12 }}
          image: "{{ .Values.frontendImage.repository }}:{{ .Values.frontendImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontendImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Values.deployment.name }}-frontend
            - configMapRef:
                name: {{ .Values.deployment.name }}-frontend
          livenessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            initialDelaySeconds: 10
            failureThreshold: 3
            httpGet:
              path: /
              port: http
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 5
            initialDelaySeconds: 5
            failureThreshold: 3
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
