apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }} frontend
spec:
  type: {{ .Values.services.frontend.type }}
  ports:
    - port: {{ .Values.services.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }} frontend
