/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * AI Evaluation API
 * OpenAPI spec version: 0.1.0
 */
import { customFetch } from "./fetcher"
export interface AppDatasetItem {
  question: string
  human_answer: string
}

/**
 * DB schema for reading an app dataset entry.
 */
export interface AppDatasetSchema {
  /** Question text */
  question: string
  /** Human-provided answer */
  human_answer: string
  /** Foreign key to apps table */
  app_id: number
  /** Unique identifier */
  id: number
  /** Timestamp when entry was created */
  created_at: string
  /** Timestamp when entry was updated */
  updated_at: string
}

export interface AppDatasetsRequest {
  datasets: AppDatasetItem[]
}

export interface AppRequest {
  name: string
  slug: string
}

export interface AppSchema {
  /**
   * Application name
   * @maxLength 100
   */
  name: string
  /**
   * URL-safe identifier (lowercase, alphanumeric, hyphens)
   * @maxLength 100
   */
  slug: string
  current_prompt_version_id?: number | null
  /** Unique identifier */
  id: number
  /** Timestamp when app was created */
  created_at: string
}

export interface ErrorResponse {
  detail: string
}

/**
 * a dict of values where the key is the dataset id and the value is the app answer to the question
 */
export type EvaluationRequestAppAnswers = { [key: string]: string }

export type EvaluationType = (typeof EvaluationType)[keyof typeof EvaluationType]

export const EvaluationType = {
  LLM_ONLY: "LLM_ONLY",
  HUMAN_AND_LLM: "HUMAN_AND_LLM",
} as const

export type LLMModel = (typeof LLMModel)[keyof typeof LLMModel]

export const LLMModel = {
  "gpt-4o-mini": "gpt-4o-mini",
  "gpt-5-mini": "gpt-5-mini",
  "claude-sonnet-4-5": "claude-sonnet-4-5",
} as const

export interface EvaluationRequest {
  app_version: string
  evaluation_type: EvaluationType
  /** a dict of values where the key is the dataset id and the value is the app answer to the question */
  app_answers: EvaluationRequestAppAnswers
  llm_judge_models: LLMModel[]
}

export interface EvaluationSummary {
  /** Application identifier */
  app_id: number
  type: EvaluationType
  version: string
  prompt_version_id: number
  /** Unique identifier */
  id: number
  /** Timestamp when evaluation was created */
  created_at: string
  /** Total number of llm judgments */
  llm_judgments_count: number
  /** Number of matching llm judgments against the human judgments if eval type is human_and_llm, otherwise number of passed llm judgments */
  llm_judgments_count_passed: number
  /** Total number of llm completed judgments */
  llm_judgments_count_completed: number
  /** Total cost for the sample */
  total_cost: number
  human_judgement_count: number
  human_judgement_count_completed: number
}

export type ValidationErrorCtx = { [key: string]: unknown }

export interface ValidationError {
  loc: (string | number)[]
  msg: string
  type: string
  input?: unknown
  ctx?: ValidationErrorCtx
}

export interface HTTPValidationError {
  detail?: ValidationError[]
}

export interface JudgmentRequest {
  reasoning: string
  passed: boolean
}

export type JudgmentType = (typeof JudgmentType)[keyof typeof JudgmentType]

export const JudgmentType = {
  HUMAN: "HUMAN",
  LLM: "LLM",
} as const

export type JudgmentStatus = (typeof JudgmentStatus)[keyof typeof JudgmentStatus]

export const JudgmentStatus = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
} as const

/**
 * DB schema for reading judgment from postgres.
 */
export interface JudgmentSchema {
  /** Foreign key to samples table */
  sample_id: number
  /** Type of judgment */
  judgment_type: JudgmentType
  /**
   * Model used by judge
   * @maxLength 50
   */
  judgment_model: string
  status: JudgmentStatus
  /** Reasoning why the score and passed mark */
  reasoning?: string | null
  /** Whether the evaluation passed */
  passed?: boolean | null
  /** Number of input tokens */
  input_tokens?: number | null
  /** Number of output tokens */
  output_tokens?: number | null
  /** Cost of input tokens */
  input_tokens_cost?: number | null
  /** Cost of output tokens */
  output_tokens_cost?: number | null
  /** Unique identifier */
  id: number
  /** Timestamp when result was created */
  created_at: string
  /** Timestamp when the row was updated */
  updated_at: string
}

export interface PromptRequest {
  /** Prompt content */
  content: string
}

export interface PromptVersionSummary {
  /** Unique identifier */
  id: number
  /** App this prompt belongs to */
  app_id: number
  /**
   * SHA-256 hash of the content
   * @maxLength 64
   */
  hash: string
  /** Prompt content */
  content: string
  /** Timestamp when prompt version was created */
  created_at: string
  llm_passed_count: number
  llm_total_count: number
  human_and_llm_matched_count: number
  human_and_llm_total_count: number
  evaluations_count: number
}

export interface SampleJudgements {
  /** Foreign key to evaluations table */
  evaluation_id: number
  /** The question asked */
  question: string
  /** The answer provided by the human (golden standard) */
  human_answer: string
  /** The answer provided by the app */
  app_answer: string
  /** Cost of the application call */
  app_cost?: number | null
  /** Unique identifier */
  id: number
  /** Timestamp when sample was created */
  created_at: string
  /** Total number of llm judgments */
  llm_judgments_count: number
  /** Number of matching llm judgments against the human judgments if eval type is human_and_llm, otherwise number of passed llm judgments */
  llm_judgments_count_passed: number
  /** Total number of llm completed judgments */
  llm_judgments_count_completed: number
  /** Total cost for the sample */
  total_cost: number
  evaluation_type: EvaluationType
  /** Whether or not the judgment passed or not. If null it means the judgment was not made yet or its a llm only evaluation. */
  human_judgment_passed: boolean | null
  human_judgment: JudgmentSchema | null
  llm_judgements: JudgmentSchema[]
}

/**
 * Lightweight sample + judgment status for navigation.
 */
export interface SampleJudgmentSummarySchema {
  /** The sample identifier */
  sample_id: number
  /** Judgment status (PENDING or COMPLETED) */
  status: string
  /** Whether the judgment passed */
  passed?: boolean | null
}

export interface SampleSummary {
  /** Foreign key to evaluations table */
  evaluation_id: number
  /** The question asked */
  question: string
  /** The answer provided by the human (golden standard) */
  human_answer: string
  /** The answer provided by the app */
  app_answer: string
  /** Cost of the application call */
  app_cost?: number | null
  /** Unique identifier */
  id: number
  /** Timestamp when sample was created */
  created_at: string
  /** Total number of llm judgments */
  llm_judgments_count: number
  /** Number of matching llm judgments against the human judgments if eval type is human_and_llm, otherwise number of passed llm judgments */
  llm_judgments_count_passed: number
  /** Total number of llm completed judgments */
  llm_judgments_count_completed: number
  /** Total cost for the sample */
  total_cost: number
  evaluation_type: EvaluationType
  /** Whether or not the judgment passed or not. If null it means the judgment was not made yet or its a llm only evaluation. */
  human_judgment_passed: boolean | null
}

export interface UpdateCurrentPromptRequest {
  /** Prompt version ID to set as current */
  prompt_id: number
}

export interface WellKnownResponse {
  issuer: string
}

export type GetEvaluationsSummariesParams = {
  eval_type: EvaluationType
}

export type GetEvaluationSamplesParams = {
  judgment_type?: JudgmentType
}

/**
 * @summary Get Well Known
 */
export type getWellKnownResponse200 = {
  data: WellKnownResponse
  status: 200
}

export type getWellKnownResponseSuccess = getWellKnownResponse200 & {
  headers: Headers
}
export type getWellKnownResponse = getWellKnownResponseSuccess

export const getGetWellKnownUrl = () => {
  return `http://127.0.0.1:8000/.well-known`
}

export const getWellKnown = async (options?: RequestInit): Promise<getWellKnownResponse> => {
  return customFetch<getWellKnownResponse>(getGetWellKnownUrl(), {
    ...options,
    method: "GET",
  })
}

/**
 * Get an app by its slug
 * @summary Get App By Slug
 */
export type getAppBySlugResponse200 = {
  data: AppSchema
  status: 200
}

export type getAppBySlugResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAppBySlugResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getAppBySlugResponseSuccess = getAppBySlugResponse200 & {
  headers: Headers
}
export type getAppBySlugResponseError = (getAppBySlugResponse404 | getAppBySlugResponse422) & {
  headers: Headers
}

export type getAppBySlugResponse = getAppBySlugResponseSuccess | getAppBySlugResponseError

export const getGetAppBySlugUrl = (slug: string) => {
  return `http://127.0.0.1:8000/v1/app/by-slug/${slug}`
}

export const getAppBySlug = async (
  slug: string,
  options?: RequestInit,
): Promise<getAppBySlugResponse> => {
  return customFetch<getAppBySlugResponse>(getGetAppBySlugUrl(slug), {
    ...options,
    method: "GET",
  })
}

/**
 * Get an app by its id
 * @summary Get App
 */
export type getAppResponse200 = {
  data: AppSchema
  status: 200
}

export type getAppResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAppResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getAppResponseSuccess = getAppResponse200 & {
  headers: Headers
}
export type getAppResponseError = (getAppResponse404 | getAppResponse422) & {
  headers: Headers
}

export type getAppResponse = getAppResponseSuccess | getAppResponseError

export const getGetAppUrl = (appId: number) => {
  return `http://127.0.0.1:8000/v1/app/${appId}`
}

export const getApp = async (appId: number, options?: RequestInit): Promise<getAppResponse> => {
  return customFetch<getAppResponse>(getGetAppUrl(appId), {
    ...options,
    method: "GET",
  })
}

/**
 * @summary Delete App
 */
export type deleteAppResponse204 = {
  data: void
  status: 204
}

export type deleteAppResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteAppResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteAppResponseSuccess = deleteAppResponse204 & {
  headers: Headers
}
export type deleteAppResponseError = (deleteAppResponse404 | deleteAppResponse422) & {
  headers: Headers
}

export type deleteAppResponse = deleteAppResponseSuccess | deleteAppResponseError

export const getDeleteAppUrl = (appId: number) => {
  return `http://127.0.0.1:8000/v1/app/${appId}`
}

export const deleteApp = async (
  appId: number,
  options?: RequestInit,
): Promise<deleteAppResponse> => {
  return customFetch<deleteAppResponse>(getDeleteAppUrl(appId), {
    ...options,
    method: "DELETE",
  })
}

/**
 * @summary Patch App
 */
export type patchAppResponse200 = {
  data: AppSchema
  status: 200
}

export type patchAppResponse404 = {
  data: ErrorResponse
  status: 404
}

export type patchAppResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type patchAppResponseSuccess = patchAppResponse200 & {
  headers: Headers
}
export type patchAppResponseError = (patchAppResponse404 | patchAppResponse422) & {
  headers: Headers
}

export type patchAppResponse = patchAppResponseSuccess | patchAppResponseError

export const getPatchAppUrl = (appId: number) => {
  return `http://127.0.0.1:8000/v1/app/${appId}`
}

export const patchApp = async (
  appId: number,
  updateCurrentPromptRequest: UpdateCurrentPromptRequest,
  options?: RequestInit,
): Promise<patchAppResponse> => {
  return customFetch<patchAppResponse>(getPatchAppUrl(appId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateCurrentPromptRequest),
  })
}

/**
 * @summary Get Apps
 */
export type getAppsResponse200 = {
  data: AppSchema[]
  status: 200
}

export type getAppsResponseSuccess = getAppsResponse200 & {
  headers: Headers
}
export type getAppsResponse = getAppsResponseSuccess

export const getGetAppsUrl = () => {
  return `http://127.0.0.1:8000/v1/app`
}

export const getApps = async (options?: RequestInit): Promise<getAppsResponse> => {
  return customFetch<getAppsResponse>(getGetAppsUrl(), {
    ...options,
    method: "GET",
  })
}

/**
 * @summary Post App
 */
export type postAppResponse201 = {
  data: unknown
  status: 201
}

export type postAppResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type postAppResponseSuccess = postAppResponse201 & {
  headers: Headers
}
export type postAppResponseError = postAppResponse422 & {
  headers: Headers
}

export type postAppResponse = postAppResponseSuccess | postAppResponseError

export const getPostAppUrl = () => {
  return `http://127.0.0.1:8000/v1/app`
}

export const postApp = async (
  appRequest: AppRequest,
  options?: RequestInit,
): Promise<postAppResponse> => {
  return customFetch<postAppResponse>(getPostAppUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(appRequest),
  })
}

/**
 * Upsert datasets for an app — inserts new questions, updates changed answers, no-ops identical entries
 * @summary Post App Datasets
 */
export type postAppDatasetsResponse200 = {
  data: AppDatasetSchema[]
  status: 200
}

export type postAppDatasetsResponse201 = {
  data: AppDatasetSchema[]
  status: 201
}

export type postAppDatasetsResponse404 = {
  data: ErrorResponse
  status: 404
}

export type postAppDatasetsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type postAppDatasetsResponseSuccess = (
  | postAppDatasetsResponse200
  | postAppDatasetsResponse201
) & {
  headers: Headers
}
export type postAppDatasetsResponseError = (
  | postAppDatasetsResponse404
  | postAppDatasetsResponse422
) & {
  headers: Headers
}

export type postAppDatasetsResponse = postAppDatasetsResponseSuccess | postAppDatasetsResponseError

export const getPostAppDatasetsUrl = (appId: number) => {
  return `http://127.0.0.1:8000/v1/app/${appId}/datasets`
}

export const postAppDatasets = async (
  appId: number,
  appDatasetsRequest: AppDatasetsRequest,
  options?: RequestInit,
): Promise<postAppDatasetsResponse> => {
  return customFetch<postAppDatasetsResponse>(getPostAppDatasetsUrl(appId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(appDatasetsRequest),
  })
}

/**
 * @summary Get App Datasets
 */
export type getAppDatasetsResponse200 = {
  data: AppDatasetSchema[]
  status: 200
}

export type getAppDatasetsResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAppDatasetsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getAppDatasetsResponseSuccess = getAppDatasetsResponse200 & {
  headers: Headers
}
export type getAppDatasetsResponseError = (
  | getAppDatasetsResponse404
  | getAppDatasetsResponse422
) & {
  headers: Headers
}

export type getAppDatasetsResponse = getAppDatasetsResponseSuccess | getAppDatasetsResponseError

export const getGetAppDatasetsUrl = (appId: number) => {
  return `http://127.0.0.1:8000/v1/app/${appId}/datasets`
}

export const getAppDatasets = async (
  appId: number,
  options?: RequestInit,
): Promise<getAppDatasetsResponse> => {
  return customFetch<getAppDatasetsResponse>(getGetAppDatasetsUrl(appId), {
    ...options,
    method: "GET",
  })
}

/**
 * Create an evaluation, evaluation is an insance of a dataset where the app answers are provided that will be judged
 * @summary Post App Evaluation
 */
export type postAppEvaluationResponse201 = {
  data: unknown
  status: 201
}

export type postAppEvaluationResponse400 = {
  data: ErrorResponse
  status: 400
}

export type postAppEvaluationResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type postAppEvaluationResponseSuccess = postAppEvaluationResponse201 & {
  headers: Headers
}
export type postAppEvaluationResponseError = (
  | postAppEvaluationResponse400
  | postAppEvaluationResponse422
) & {
  headers: Headers
}

export type postAppEvaluationResponse =
  | postAppEvaluationResponseSuccess
  | postAppEvaluationResponseError

export const getPostAppEvaluationUrl = (appId: number) => {
  return `http://127.0.0.1:8000/v1/app/${appId}/evaluation`
}

export const postAppEvaluation = async (
  appId: number,
  evaluationRequest: EvaluationRequest,
  options?: RequestInit,
): Promise<postAppEvaluationResponse> => {
  return customFetch<postAppEvaluationResponse>(getPostAppEvaluationUrl(appId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(evaluationRequest),
  })
}

/**
 * @summary Get App Prompts
 */
export type getAppPromptResponse200 = {
  data: PromptVersionSummary[]
  status: 200
}

export type getAppPromptResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAppPromptResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getAppPromptResponseSuccess = getAppPromptResponse200 & {
  headers: Headers
}
export type getAppPromptResponseError = (getAppPromptResponse404 | getAppPromptResponse422) & {
  headers: Headers
}

export type getAppPromptResponse = getAppPromptResponseSuccess | getAppPromptResponseError

export const getGetAppPromptUrl = (appId: number) => {
  return `http://127.0.0.1:8000/v1/app/${appId}/prompt`
}

export const getAppPrompt = async (
  appId: number,
  options?: RequestInit,
): Promise<getAppPromptResponse> => {
  return customFetch<getAppPromptResponse>(getGetAppPromptUrl(appId), {
    ...options,
    method: "GET",
  })
}

/**
 * @summary Post App Prompt
 */
export type postAppPromptResponse201 = {
  data: PromptVersionSummary
  status: 201
}

export type postAppPromptResponse404 = {
  data: ErrorResponse
  status: 404
}

export type postAppPromptResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type postAppPromptResponseSuccess = postAppPromptResponse201 & {
  headers: Headers
}
export type postAppPromptResponseError = (postAppPromptResponse404 | postAppPromptResponse422) & {
  headers: Headers
}

export type postAppPromptResponse = postAppPromptResponseSuccess | postAppPromptResponseError

export const getPostAppPromptUrl = (appId: number) => {
  return `http://127.0.0.1:8000/v1/app/${appId}/prompt`
}

export const postAppPrompt = async (
  appId: number,
  promptRequest: PromptRequest,
  options?: RequestInit,
): Promise<postAppPromptResponse> => {
  return customFetch<postAppPromptResponse>(getPostAppPromptUrl(appId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(promptRequest),
  })
}

/**
 * @summary Get Evaluations
 */
export type getEvaluationsSummariesResponse200 = {
  data: EvaluationSummary[]
  status: 200
}

export type getEvaluationsSummariesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getEvaluationsSummariesResponseSuccess = getEvaluationsSummariesResponse200 & {
  headers: Headers
}
export type getEvaluationsSummariesResponseError = getEvaluationsSummariesResponse422 & {
  headers: Headers
}

export type getEvaluationsSummariesResponse =
  | getEvaluationsSummariesResponseSuccess
  | getEvaluationsSummariesResponseError

export const getGetEvaluationsSummariesUrl = (
  appId: number,
  params: GetEvaluationsSummariesParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `http://127.0.0.1:8000/v1/app/${appId}/evaluation/summary?${stringifiedParams}`
    : `http://127.0.0.1:8000/v1/app/${appId}/evaluation/summary`
}

export const getEvaluationsSummaries = async (
  appId: number,
  params: GetEvaluationsSummariesParams,
  options?: RequestInit,
): Promise<getEvaluationsSummariesResponse> => {
  return customFetch<getEvaluationsSummariesResponse>(
    getGetEvaluationsSummariesUrl(appId, params),
    {
      ...options,
      method: "GET",
    },
  )
}

/**
 * Add a judgement to a sample, used for human judging
 * @summary Post Sample
 */
export type postJudgmentResponse201 = {
  data: unknown
  status: 201
}

export type postJudgmentResponse400 = {
  data: ErrorResponse
  status: 400
}

export type postJudgmentResponse404 = {
  data: ErrorResponse
  status: 404
}

export type postJudgmentResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type postJudgmentResponseSuccess = postJudgmentResponse201 & {
  headers: Headers
}
export type postJudgmentResponseError = (
  | postJudgmentResponse400
  | postJudgmentResponse404
  | postJudgmentResponse422
) & {
  headers: Headers
}

export type postJudgmentResponse = postJudgmentResponseSuccess | postJudgmentResponseError

export const getPostJudgmentUrl = (sampleId: number) => {
  return `http://127.0.0.1:8000/v1/sample/${sampleId}/judgment`
}

export const postJudgment = async (
  sampleId: number,
  judgmentRequest: JudgmentRequest,
  options?: RequestInit,
): Promise<postJudgmentResponse> => {
  return customFetch<postJudgmentResponse>(getPostJudgmentUrl(sampleId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(judgmentRequest),
  })
}

/**
 * @summary Get Sample
 */
export type getSampleDetailResponse200 = {
  data: SampleJudgements
  status: 200
}

export type getSampleDetailResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getSampleDetailResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getSampleDetailResponseSuccess = getSampleDetailResponse200 & {
  headers: Headers
}
export type getSampleDetailResponseError = (
  | getSampleDetailResponse404
  | getSampleDetailResponse422
) & {
  headers: Headers
}

export type getSampleDetailResponse = getSampleDetailResponseSuccess | getSampleDetailResponseError

export const getGetSampleDetailUrl = (sampleId: number) => {
  return `http://127.0.0.1:8000/v1/sample/${sampleId}`
}

export const getSampleDetail = async (
  sampleId: number,
  options?: RequestInit,
): Promise<getSampleDetailResponse> => {
  return customFetch<getSampleDetailResponse>(getGetSampleDetailUrl(sampleId), {
    ...options,
    method: "GET",
  })
}

/**
 * @summary Get Evaluation Samples Summaries
 */
export type getSamplesSummariesResponse200 = {
  data: SampleSummary[]
  status: 200
}

export type getSamplesSummariesResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getSamplesSummariesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getSamplesSummariesResponseSuccess = getSamplesSummariesResponse200 & {
  headers: Headers
}
export type getSamplesSummariesResponseError = (
  | getSamplesSummariesResponse404
  | getSamplesSummariesResponse422
) & {
  headers: Headers
}

export type getSamplesSummariesResponse =
  | getSamplesSummariesResponseSuccess
  | getSamplesSummariesResponseError

export const getGetSamplesSummariesUrl = (evaluationId: number) => {
  return `http://127.0.0.1:8000/v1/evaluation/${evaluationId}/sample/summary`
}

export const getSamplesSummaries = async (
  evaluationId: number,
  options?: RequestInit,
): Promise<getSamplesSummariesResponse> => {
  return customFetch<getSamplesSummariesResponse>(getGetSamplesSummariesUrl(evaluationId), {
    ...options,
    method: "GET",
  })
}

/**
 * @summary Get Evaluation Samples
 */
export type getEvaluationSamplesResponse200 = {
  data: SampleJudgmentSummarySchema[]
  status: 200
}

export type getEvaluationSamplesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getEvaluationSamplesResponseSuccess = getEvaluationSamplesResponse200 & {
  headers: Headers
}
export type getEvaluationSamplesResponseError = getEvaluationSamplesResponse422 & {
  headers: Headers
}

export type getEvaluationSamplesResponse =
  | getEvaluationSamplesResponseSuccess
  | getEvaluationSamplesResponseError

export const getGetEvaluationSamplesUrl = (
  evaluationId: number,
  params?: GetEvaluationSamplesParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `http://127.0.0.1:8000/v1/evaluation/${evaluationId}/sample/judgment?${stringifiedParams}`
    : `http://127.0.0.1:8000/v1/evaluation/${evaluationId}/sample/judgment`
}

export const getEvaluationSamples = async (
  evaluationId: number,
  params?: GetEvaluationSamplesParams,
  options?: RequestInit,
): Promise<getEvaluationSamplesResponse> => {
  return customFetch<getEvaluationSamplesResponse>(
    getGetEvaluationSamplesUrl(evaluationId, params),
    {
      ...options,
      method: "GET",
    },
  )
}
