"""remove hash uniquines

Revision ID: 719ff1882c0a
Revises: a1b2c3d4e5f6
Create Date: 2026-02-08 21:34:45.383142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719ff1882c0a'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_prompt_versions_app_id_hash'), 'prompt_versions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_prompt_versions_app_id_hash'), 'prompt_versions', ['app_id', 'hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
