"""move fk for prompt

Revision ID: 206a1cd525d7
Revises: ffcaa99fa234
Create Date: 2026-02-08 19:54:12.405597

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "206a1cd525d7"
down_revision: Union[str, Sequence[str], None] = "ffcaa99fa234"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_evaluations_prompt_version_id_prompt_versions"),
        "evaluations",
        type_="foreignkey",
    )
    op.drop_column("evaluations", "prompt_version_id")
    op.add_column(
        "judgments",
        sa.Column("prompt_version_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_judgments_prompt_version_id_prompt_versions"),
        "judgments",
        "prompt_versions",
        ["prompt_version_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_judgments_prompt_version_id_prompt_versions"),
        "judgments",
        type_="foreignkey",
    )
    op.drop_column("judgments", "prompt_version_id")
    op.add_column(
        "evaluations",
        sa.Column(
            "prompt_version_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f("fk_evaluations_prompt_version_id_prompt_versions"),
        "evaluations",
        "prompt_versions",
        ["prompt_version_id"],
        ["id"],
    )
    # ### end Alembic commands ###
