"""adjust judge table

Revision ID: 4c8f110e9c1a
Revises: 1bcdbd9bf608
Create Date: 2026-01-19 13:30:26.607786

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c8f110e9c1a"
down_revision: Union[str, Sequence[str], None] = "1bcdbd9bf608"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "judge_results", sa.Column("status", sa.String(length=50), nullable=False)
    )
    op.alter_column(
        "judge_results",
        "judge_model",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "judge_results", "reasoning", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "judge_results", "passed", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column("judge_results", "score", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "judge_results", "score", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "judge_results", "passed", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "judge_results", "reasoning", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "judge_results",
        "judge_model",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.drop_column("judge_results", "status")
    # ### end Alembic commands ###
