"""add app answer

Revision ID: cbe06dc65990
Revises: 1bcdbd9bf608
Create Date: 2026-01-27 20:48:58.613928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe06dc65990'
down_revision: Union[str, Sequence[str], None] = '1bcdbd9bf608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('human_answer', sa.Text(), nullable=False))
    op.add_column('samples', sa.Column('app_answer', sa.Text(), nullable=False))
    op.drop_column('samples', 'answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('samples', 'app_answer')
    op.drop_column('samples', 'human_answer')
    # ### end Alembic commands ###
