"""drop hash column from prompt_versions

Revision ID: 1b6aee173f8b
Revises: 910b58348fe8
Create Date: 2026-02-08 21:26:02.242010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6aee173f8b'
down_revision: Union[str, Sequence[str], None] = '910b58348fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_versions', 'hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_versions', sa.Column('hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
