"""add prompt versions

Revision ID: ffcaa99fa234
Revises: d499de60548c
Create Date: 2026-02-08 11:11:49.167759

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffcaa99fa234"
down_revision: Union[str, Sequence[str], None] = "d499de60548c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_versions",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_prompt_versions")
        ),
        sa.UniqueConstraint(
            "hash", name=op.f("uq_prompt_versions_hash")
        ),
    )
    op.add_column(
        "apps",
        sa.Column(
            "current_prompt_version_id", sa.Integer(), nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("fk_apps_current_prompt_version_id_prompt_versions"),
        "apps",
        "prompt_versions",
        ["current_prompt_version_id"],
        ["id"],
    )
    op.add_column(
        "evaluations",
        sa.Column("prompt_version_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_evaluations_prompt_version_id_prompt_versions"),
        "evaluations",
        "prompt_versions",
        ["prompt_version_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_evaluations_prompt_version_id_prompt_versions"),
        "evaluations",
        type_="foreignkey",
    )
    op.drop_column("evaluations", "prompt_version_id")
    op.drop_constraint(
        op.f("fk_apps_current_prompt_version_id_prompt_versions"),
        "apps",
        type_="foreignkey",
    )
    op.drop_column("apps", "current_prompt_version_id")
    op.drop_table("prompt_versions")
    # ### end Alembic commands ###
