"""add updated at to judge table

Revision ID: 54de4a445ca3
Revises: 6c5a06f3afec
Create Date: 2026-01-19 14:08:00.199294

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54de4a445ca3"
down_revision: Union[str, Sequence[str], None] = "6c5a06f3afec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "judges",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("judges", "updated_at")
    # ### end Alembic commands ###
