"""add apps table

Revision ID: 8290dd56a54c
Revises: 4005bc2ee1ee
Create Date: 2026-02-07 11:56:33.807162

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8290dd56a54c"
down_revision: Union[str, Sequence[str], None] = "4005bc2ee1ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apps",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_apps")),
    )
    op.add_column(
        "evaluations",
        sa.Column("version", sa.String(length=50), nullable=False),
    )
    op.alter_column(
        "evaluations",
        "app_id",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.create_foreign_key(
        op.f("fk_evaluations_app_id_apps"),
        "evaluations",
        "apps",
        ["app_id"],
        ["id"],
    )
    op.drop_column("evaluations", "app_version")
    op.drop_column("evaluations", "metadata")
    op.drop_column("samples", "metadata")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "samples",
        sa.Column(
            "metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "evaluations",
        sa.Column(
            "metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "evaluations",
        sa.Column(
            "app_version",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("fk_evaluations_app_id_apps"),
        "evaluations",
        type_="foreignkey",
    )
    op.alter_column(
        "evaluations",
        "app_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_column("evaluations", "version")
    op.drop_table("apps")
    # ### end Alembic commands ###
