"""add cascade delete to all foreign keys

Revision ID: d499de60548c
Revises: 769abf8a9d73
Create Date: 2026-02-08 10:01:00.354960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd499de60548c'
down_revision: Union[str, Sequence[str], None] = '769abf8a9d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_app_datasets_app_id_apps'), 'app_datasets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_app_datasets_app_id_apps'), 'app_datasets', 'apps', ['app_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_evaluations_app_id_apps'), 'evaluations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_evaluations_app_id_apps'), 'evaluations', 'apps', ['app_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_judgments_sample_id_samples'), 'judgments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_judgments_sample_id_samples'), 'judgments', 'samples', ['sample_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_samples_evaluation_id_evaluations'), 'samples', type_='foreignkey')
    op.create_foreign_key(op.f('fk_samples_evaluation_id_evaluations'), 'samples', 'evaluations', ['evaluation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_samples_evaluation_id_evaluations'), 'samples', type_='foreignkey')
    op.create_foreign_key(op.f('fk_samples_evaluation_id_evaluations'), 'samples', 'evaluations', ['evaluation_id'], ['id'])
    op.drop_constraint(op.f('fk_judgments_sample_id_samples'), 'judgments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_judgments_sample_id_samples'), 'judgments', 'samples', ['sample_id'], ['id'])
    op.drop_constraint(op.f('fk_evaluations_app_id_apps'), 'evaluations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_evaluations_app_id_apps'), 'evaluations', 'apps', ['app_id'], ['id'])
    op.drop_constraint(op.f('fk_app_datasets_app_id_apps'), 'app_datasets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_app_datasets_app_id_apps'), 'app_datasets', 'apps', ['app_id'], ['id'])
    # ### end Alembic commands ###
