deployment:
  env: prod

app:
  env: prod
  logLevel: INFO

api:
  replicas: 2
  serviceBaseUrl: https://api.verdikt.prod.example.com
  oidc:
    issuer: https://accounts.google.com
    audience: ""

frontend:
  replicas: 2
  oidc:
    issuer: https://accounts.google.com

access:
  admins:
    - admin@example.com
  apps: {}

postgres:
  host: null # prod DB host

ingress:
  hosts:
    - host: verdikt.prod.example.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
    - host: api.verdikt.prod.example.com
      paths:
        - path: /
          pathType: Prefix
          service: api
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
  tls:
    - secretName: verdikt-prod-tls
      hosts:
        - verdikt.prod.example.com
        - api.verdikt.prod.example.com
