deployment:
  env: dev

app:
  env: dev
  logLevel: DEBUG

api:
  serviceBaseUrl: https://api.verdikt.dev.example.com
  oidc:
    issuer: https://accounts.google.com
    audience: ""

frontend:
  oidc:
    issuer: https://accounts.google.com

access:
  admins:
    - admin@example.com
  apps: {}

postgres:
  host: null # dev DB host

ingress:
  hosts:
    - host: verdikt.dev.example.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
    - host: api.verdikt.dev.example.com
      paths:
        - path: /
          pathType: Prefix
          service: api
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
  tls:
    - secretName: verdikt-dev-tls
      hosts:
        - verdikt.dev.example.com
        - api.verdikt.dev.example.com
