"""move prompt_id to evaluations

Revision ID: e75178bca5b8
Revises: 719ff1882c0a
Create Date: 2026-02-09 21:40:53.398624

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e75178bca5b8"
down_revision: Union[str, Sequence[str], None] = "719ff1882c0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "evaluations",
        sa.Column("prompt_version_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_evaluations_prompt_version_id_prompt_versions"),
        "evaluations",
        "prompt_versions",
        ["prompt_version_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_judgments_prompt_version_id_prompt_versions"),
        "judgments",
        type_="foreignkey",
    )
    op.drop_column("judgments", "prompt_version_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "judgments",
        sa.Column(
            "prompt_version_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f("fk_judgments_prompt_version_id_prompt_versions"),
        "judgments",
        "prompt_versions",
        ["prompt_version_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_evaluations_prompt_version_id_prompt_versions"),
        "evaluations",
        type_="foreignkey",
    )
    op.drop_column("evaluations", "prompt_version_id")
    # ### end Alembic commands ###
