"""app principals

Revision ID: e76d615a5dbe
Revises: 0ea21177c7b1
Create Date: 2026-06-26 18:57:43.946545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76d615a5dbe'
down_revision: Union[str, Sequence[str], None] = '0ea21177c7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_principals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], name=op.f('fk_app_principals_app_id_apps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_principals')),
    sa.UniqueConstraint('app_id', 'subject_type', 'subject', name=op.f('uq_app_principals_app_id_subject_type_subject'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_principals')
    # ### end Alembic commands ###
