name: be-tests

on: [push]

jobs:
  be-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    env:
      PG_PORT: "5432"

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: evaluation
          POSTGRES_PASSWORD: alpharius
          POSTGRES_DB: evaluation
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install 3.13

      - name: Run tests
        run: uv run pytest -v tests/
