variables:
  TF_DIR_DEV: terraform/dev
  TF_DIR_PRE_PROD: terraform/pre-prod
  TF_DIR_PROD: terraform/prod

stages:
  - terraform-plan
  - terraform-apply

.terraform-plan:
  image: devopsinfra/docker-terragrunt:gcp-tf-1.13.0-tg-0.86.2
  stage: terraform-plan
  tags:
    - gcp
  before_script:
    - cd $TF_DIR
    - echo "$SA_KEY" > ${HOME}/deployer-key.json
    - export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/deployer-key.json
    - shopt -s expand_aliases
  script:
    - terraform init -upgrade
    - terraform plan -lock-timeout=5m -out ../../plan.cache
  artifacts:
    name: plan
    paths:
      - plan.cache
  needs: []
  except:
    refs:
      - pipelines


.terraform-apply:
  image: devopsinfra/docker-terragrunt:gcp-tf-1.13.0-tg-0.86.2
  stage: terraform-apply
  tags:
    - gcp
  before_script:
    - cd $TF_DIR
    - echo "$SA_KEY" > ${HOME}/deployer-key.json
    - export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/deployer-key.json
    - shopt -s expand_aliases
  script:
    - terraform init -upgrade
    - terraform apply -input=false ../../plan.cache
  except:
    refs:
      - pipelines
  only:
    refs:
      - master
  when: manual

dev.terraform-plan:
  extends: .terraform-plan
  environment: dev
  variables:
    TF_DIR: $TF_DIR_DEV
    SA_KEY: $TF_SA_KEY


pre-prod.terraform-plan:
  extends: .terraform-plan
  environment: pre-prod
  variables:
    TF_DIR: $TF_DIR_PRE_PROD
    SA_KEY: $TF_SA_KEY

prod.terraform-plan:
  extends: .terraform-plan
  environment: prod
  variables:
    TF_DIR: $TF_DIR_PROD
    SA_KEY: $TF_SA_KEY

dev.terraform-apply:
  extends: .terraform-apply
  environment: dev
  dependencies:
    - dev.terraform-plan
  variables:
    TF_DIR: $TF_DIR_DEV
    SA_KEY: $TF_SA_KEY
  needs:
    - dev.terraform-plan

pre-prod.terraform-apply:
  extends: .terraform-apply
  environment: pre-prod
  dependencies:
    - pre-prod.terraform-plan
  variables:
    TF_DIR: $TF_DIR_PRE_PROD
    SA_KEY: $TF_SA_KEY
  needs:
    - pre-prod.terraform-plan

prod.terraform-apply:
  extends: .terraform-apply
  environment: prod
  dependencies:
    - prod.terraform-plan
  variables:
    TF_DIR: $TF_DIR_PROD
    SA_KEY: $TF_SA_KEY
  needs:
    - prod.terraform-plan
